export enum JournalEntry {
    TurnStart,
    FightStart,
    FightEnd,
    FightResult,
    FightAttack,
    FightAttackResult,
    FightEvade,
    FightEvadeResult,
    DoorOpen,
    DoorClose,
    PlayerAbandon,
    PlayerWin,
    GameEnd,
}
